[Variables]
codeName.Intel=" (Sandy Bridge)":""," (Ivy Bridge)":""," (Haswell)":""," (Broadwell)":""," (Skylake)":""," (Kaby Lake)":""," (Kaby Lake Refresh)":""," (Coffee Lake)":""," (Cannon Lake)":""," (Ice Lake)":""," (Rocket Lake)":""," (Alder Lake)":""
codeName.AMD=" (Summit Ridge)":""," (Pinnacle Ridge)":""," (Matisse)":""," (Vermeer)":""," (Raphael)":""
text.Color=255,255,255,255
text.Face=FontFace
text.Size=10

[styleText]
FontColor=#text.Color#
FontFace=#text.Face#
FontSize=#text.Size#
AntiAlias=1

[Background]
Meter=Image
W=245
H=125
SolidColor=5,5,5,100